import { Metadata } from 'next';
import AboutClient from '@/components/AboutClient';

export const metadata: Metadata = {
  title: "About Sirat AI | The Future of Authenticated Islamic Wisdom & AI",
  description: "Discover how Sirat AI merges 1400 years of traditional Islamic scholarship with advanced neural networks to provide verified, context-aware answers to modern life challenges.",
  keywords: ["Islamic AI", "Authenticated Islamic Wisdom", "Sirat AI Mission", "Quran and Hadith AI Assistant", "Halal AI Platform", "Non-Sectarian Islamic Hub"],
  alternates: {
    canonical: 'https://sirat.ai/about',
  },
  openGraph: {
    title: "About Sirat AI | Authenticated Islamic Wisdom",
    description: "Explore the mission behind Sirat AI — bridging classical Fiqh with cutting-edge artificial intelligence for the global Ummah.",
    url: 'https://sirat.ai/about',
    siteName: 'Sirat AI',
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: "About Sirat AI | Authenticated Islamic Wisdom",
    description: "Discover how Sirat AI delivers verified Islamic knowledge through advanced AI.",
  },
};

export default function AboutPageServer() {
  return (
    <>
      {/* Advanced Structured Data (Organization + FAQ Schema for Google #1 Ranking) */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@graph": [
              {
                "@type": "AboutPage",
                "@id": "https://sirat.ai/about",
                "url": "https://sirat.ai/about",
                "name": "About Sirat AI",
                "description": "Sirat AI is the leading platform for authenticated Islamic wisdom through AI. Learn about our mission, scholarly verification process, and commitment to privacy.",
                "publisher": {
                  "@type": "Organization",
                  "name": "Sirat AI",
                  "url": "https://sirat.ai",
                  "logo": "https://sirat.ai/sirat-ai-logo.png"
                }
              },
              {
                "@type": "FAQPage",
                "mainEntity": [
                  {
                    "@type": "Question",
                    "name": "What is Sirat AI?",
                    "acceptedAnswer": {
                      "@type": "Answer",
                      "text": "Sirat AI is the world's premier AI-driven digital hub designed to provide verified, context-aware Islamic knowledge derived directly from the Quran, Sahih Hadith, and classical Fiqh."
                    }
                  },
                  {
                    "@type": "Question",
                    "name": "How does Sirat AI verify its answers?",
                    "acceptedAnswer": {
                      "@type": "Answer",
                      "text": "Every response generated by Sirat AI is anchored in authenticated scholarly datasets and verified through strict source citations, ensuring complete freedom from weak narrations or sectarian bias."
                    }
                  },
                  {
                    "@type": "Question",
                    "name": "Is Sirat AI free for the global Ummah?",
                    "acceptedAnswer": {
                      "@type": "Answer",
                      "text": "Yes, Sirat AI is completely free and accessible to all believers worldwide as an ongoing Sadaqah Jariyah to spread authentic Islamic knowledge."
                    }
                  }
                ]
              }
            ]
          }),
        }}
      />
      <AboutClient />
    </>
  );
}